baseURL = 'http://richardsrecipies.co.uk'
locale = 'en-uk'
title = '''Richard's Recipes'''
theme = 'hugo-book'

[params]
  enableGitInfo = true
  BookTheme = 'dark'
  BookSection = 'recipes'

[deployment]
  [[deployment.targets]]
    name = 'aws'
    url = 's3://richardsrecipiesbucket?region=eu-north-1'
